import { Injectable, signal } from '@angular/core';

export type Lang = 'es' | 'en';

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private _lang = signal<Lang>((localStorage.getItem('lang') as Lang) || 'es');
  lang = this._lang.asReadonly();

  private translations: Record<Lang, Record<string, string>> = {
    es: {
      // Navbar
      'nav.home': 'Inicio',
      'nav.products': 'Productos',
      'nav.cart': 'Carrito',
      'nav.login': 'Iniciar sesión',
      'nav.logout': 'Cerrar sesión',
      'nav.register': 'Registrarse',
      'nav.account': 'Mi cuenta',
      'nav.search': 'Buscar productos o marcas...',
      'nav.dark': 'Modo oscuro',
      'nav.light': 'Modo claro',
      // Home
      'home.hero.title': 'La mejor tecnología',
      'home.hero.subtitle': 'Encuentra los mejores productos de tecnología al mejor precio',
      'home.hero.btn': 'Ver productos',
      'home.categories': 'Categorías',
      'home.featured': 'Productos Destacados',
      'home.newArrivals': 'Novedades',
      'home.offers': 'Ofertas',
      'home.viewAll': 'Ver todos',
      // Productos
      'product.addToCart': 'Añadir al carrito',
      'product.stock': 'En stock',
      'product.outOfStock': 'Sin stock',
      'product.details': 'Ver detalles',
      'product.description': 'Descripción',
      'product.specs': 'Especificaciones',
      'product.reviews': 'Reseñas',
      'product.noReviews': 'No hay reseñas todavía. ¡Sé el primero en opinar!',
      'product.addReview': 'Escribir reseña',
      'product.yourRating': 'Tu valoración',
      'product.yourComment': 'Tu comentario',
      'product.submitReview': 'Publicar reseña',
      'product.brand': 'Marca',
      'product.category': 'Categoría',
      'product.price': 'Precio',
      'product.related': 'Productos relacionados',
      // Buscador
      'search.title': 'Resultados de búsqueda',
      'search.for': 'para',
      'search.noResults': 'No se encontraron productos para',
      'search.results': 'resultado(s)',
      'search.filterBy': 'Filtrar por',
      'search.sortBy': 'Ordenar por',
      'search.sort.nameAsc': 'Nombre A-Z',
      'search.sort.nameDesc': 'Nombre Z-A',
      'search.sort.priceAsc': 'Precio: menor a mayor',
      'search.sort.priceDesc': 'Precio: mayor a menor',
      // Carrito
      'cart.title': 'Tu carrito',
      'cart.empty': 'Tu carrito está vacío',
      'cart.emptyMsg': 'Añade productos para continuar',
      'cart.continueShopping': 'Seguir comprando',
      'cart.checkout': 'Tramitar pedido',
      'cart.total': 'Total',
      'cart.subtotal': 'Subtotal',
      'cart.remove': 'Eliminar',
      'cart.quantity': 'Cantidad',
      'cart.items': 'artículo(s)',
      // Checkout
      'checkout.title': 'Finalizar pedido',
      'checkout.shipping': 'Dirección de envío',
      'checkout.summary': 'Resumen del pedido',
      'checkout.name': 'Nombre',
      'checkout.apellidos': 'Apellidos',
      'checkout.email': 'Email',
      'checkout.phone': 'Teléfono',
      'checkout.address': 'Dirección',
      'checkout.city': 'Ciudad',
      'checkout.province': 'Provincia',
      'checkout.cp': 'Código postal',
      'checkout.country': 'País',
      'checkout.placeOrder': 'Realizar pedido',
      'checkout.noPayment': 'Proyecto TFG - Pago no disponible',
      'checkout.success': '¡Pedido realizado con éxito!',
      'checkout.successMsg': 'Tu pedido ha sido registrado. Recibirás confirmación por email.',
      'checkout.backHome': 'Volver al inicio',
      // Login
      'login.title': 'Iniciar sesión',
      'login.email': 'Correo electrónico',
      'login.password': 'Contraseña',
      'login.submit': 'Entrar',
      'login.noAccount': '¿No tienes cuenta?',
      'login.register': 'Regístrate',
      'login.error': 'Email o contraseña incorrectos',
      'login.forgotPassword': '¿Olvidaste tu contraseña?',
      // Register
      'register.title': 'Crear cuenta',
      'register.name': 'Nombre',
      'register.apellidos': 'Apellidos',
      'register.email': 'Correo electrónico',
      'register.password': 'Contraseña',
      'register.confirmPassword': 'Confirmar contraseña',
      'register.phone': 'Teléfono (opcional)',
      'register.submit': 'Crear cuenta',
      'register.hasAccount': '¿Ya tienes cuenta?',
      'register.login': 'Inicia sesión',
      'register.success': 'Cuenta creada con éxito',
      'register.passwordMismatch': 'Las contraseñas no coinciden',
      'register.emailExists': 'Este email ya está registrado',
      // General
      'general.loading': 'Cargando...',
      'general.error': 'Ha ocurrido un error',
      'general.back': 'Volver',
      'general.close': 'Cerrar',
      'general.save': 'Guardar',
      'general.cancel': 'Cancelar',
      'general.confirm': 'Confirmar',
      'general.required': 'Este campo es obligatorio',
      // Categorías
      'cat.smartphones': 'Smartphones',
      'cat.laptops': 'Portátiles',
      'cat.tablets': 'Tablets',
      'cat.tvs': 'Televisores',
      'cat.headphones': 'Auriculares',
      'cat.smartwatches': 'Smartwatches',
      'cat.consoles': 'Consolas',
      'cat.accessories': 'Accesorios',
      // Footer
      'footer.rights': 'Todos los derechos reservados',
      'footer.tfg': 'Proyecto TFG - DAM',
      'footer.contact': 'Contacto',
      'footer.about': 'Acerca de',
    },
    en: {
      // Navbar
      'nav.home': 'Home',
      'nav.products': 'Products',
      'nav.cart': 'Cart',
      'nav.login': 'Login',
      'nav.logout': 'Logout',
      'nav.register': 'Register',
      'nav.account': 'My account',
      'nav.search': 'Search products or brands...',
      'nav.dark': 'Dark mode',
      'nav.light': 'Light mode',
      // Home
      'home.hero.title': 'The best technology',
      'home.hero.subtitle': 'Find the best tech products at the best price',
      'home.hero.btn': 'View products',
      'home.categories': 'Categories',
      'home.featured': 'Featured Products',
      'home.newArrivals': 'New Arrivals',
      'home.offers': 'Offers',
      'home.viewAll': 'View all',
      // Productos
      'product.addToCart': 'Add to cart',
      'product.stock': 'In stock',
      'product.outOfStock': 'Out of stock',
      'product.details': 'View details',
      'product.description': 'Description',
      'product.specs': 'Specifications',
      'product.reviews': 'Reviews',
      'product.noReviews': 'No reviews yet. Be the first to review!',
      'product.addReview': 'Write a review',
      'product.yourRating': 'Your rating',
      'product.yourComment': 'Your comment',
      'product.submitReview': 'Post review',
      'product.brand': 'Brand',
      'product.category': 'Category',
      'product.price': 'Price',
      'product.related': 'Related products',
      // Buscador
      'search.title': 'Search results',
      'search.for': 'for',
      'search.noResults': 'No products found for',
      'search.results': 'result(s)',
      'search.filterBy': 'Filter by',
      'search.sortBy': 'Sort by',
      'search.sort.nameAsc': 'Name A-Z',
      'search.sort.nameDesc': 'Name Z-A',
      'search.sort.priceAsc': 'Price: low to high',
      'search.sort.priceDesc': 'Price: high to low',
      // Carrito
      'cart.title': 'Your cart',
      'cart.empty': 'Your cart is empty',
      'cart.emptyMsg': 'Add products to continue',
      'cart.continueShopping': 'Continue shopping',
      'cart.checkout': 'Proceed to checkout',
      'cart.total': 'Total',
      'cart.subtotal': 'Subtotal',
      'cart.remove': 'Remove',
      'cart.quantity': 'Quantity',
      'cart.items': 'item(s)',
      // Checkout
      'checkout.title': 'Complete order',
      'checkout.shipping': 'Shipping address',
      'checkout.summary': 'Order summary',
      'checkout.name': 'First name',
      'checkout.apellidos': 'Last name',
      'checkout.email': 'Email',
      'checkout.phone': 'Phone',
      'checkout.address': 'Address',
      'checkout.city': 'City',
      'checkout.province': 'Province',
      'checkout.cp': 'Postal code',
      'checkout.country': 'Country',
      'checkout.placeOrder': 'Place order',
      'checkout.noPayment': 'TFG Project - Payment not available',
      'checkout.success': 'Order placed successfully!',
      'checkout.successMsg': 'Your order has been registered. You will receive a confirmation by email.',
      'checkout.backHome': 'Back to home',
      // Login
      'login.title': 'Login',
      'login.email': 'Email address',
      'login.password': 'Password',
      'login.submit': 'Sign in',
      'login.noAccount': "Don't have an account?",
      'login.register': 'Register',
      'login.error': 'Incorrect email or password',
      'login.forgotPassword': 'Forgot your password?',
      // Register
      'register.title': 'Create account',
      'register.name': 'First name',
      'register.apellidos': 'Last name',
      'register.email': 'Email address',
      'register.password': 'Password',
      'register.confirmPassword': 'Confirm password',
      'register.phone': 'Phone (optional)',
      'register.submit': 'Create account',
      'register.hasAccount': 'Already have an account?',
      'register.login': 'Sign in',
      'register.success': 'Account created successfully',
      'register.passwordMismatch': 'Passwords do not match',
      'register.emailExists': 'This email is already registered',
      // General
      'general.loading': 'Loading...',
      'general.error': 'An error occurred',
      'general.back': 'Back',
      'general.close': 'Close',
      'general.save': 'Save',
      'general.cancel': 'Cancel',
      'general.confirm': 'Confirm',
      'general.required': 'This field is required',
      // Categorías
      'cat.smartphones': 'Smartphones',
      'cat.laptops': 'Laptops',
      'cat.tablets': 'Tablets',
      'cat.tvs': 'TVs',
      'cat.headphones': 'Headphones',
      'cat.smartwatches': 'Smartwatches',
      'cat.consoles': 'Consoles',
      'cat.accessories': 'Accessories',
      // Footer
      'footer.rights': 'All rights reserved',
      'footer.tfg': 'TFG Project - DAM',
      'footer.contact': 'Contact',
      'footer.about': 'About',
    },
  };

  t(key: string): string {
    return this.translations[this._lang()][key] ?? key;
  }

  setLang(lang: Lang): void {
    this._lang.set(lang);
    localStorage.setItem('lang', lang);
  }

  toggleLang(): void {
    this.setLang(this._lang() === 'es' ? 'en' : 'es');
  }
}
